---
name: lint
on: [push, pull_request]
permissions:
  contents: read
env:
  FORCE_COLOR: 1
  MYPY_FORCE_COLOR: 1
  PY_COLORS: 1
  TOX_TESTENV_PASSENV: >-
    FORCE_COLOR
    MYPY_FORCE_COLOR
    NO_COLOR
    PY_COLORS
    PYTEST_THEME
    PYTEST_THEME_MODE
  TOX_PARALLEL_NO_SPINNER: 1
jobs:
  lint:
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    continue-on-error: ${{ matrix.python == '3.12' }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
      - name: Install Packages
        run: |
          python -m pip install .[tests]
      - name: Run ruff
        run: ruff src
      - name: Run mypy
        run: mypy src
      - name: Run black
        run: black src
